
GlobalVariable = {
	NotificationTag = {
		CHANGE_QUEUE = "NotificationTag_CHANGE_QUEUE",
        UPDATA_MEMBERS_SCENE = "NotificationTag_UPDATA_MEMBERS_SCENE",
        EQUIPMENT_ENHANCE_LAYER = "NotificationTag_EQUIPMENT_ENHANCE_LAYER",
        EQUIPMENT_DETAIL_LAYER = "NotificationTag_EQUIPMENT_DETAIL_LAYER",
        EQUIPMENT_DOUBLE_DETAIL = "NotificationTag_EQUIPMENT_DOUBLE_LAYER_DETAIL",
        EQUIPMENT_DOUBLE_INHANCE = "NotificationTag_EQUIPMENT_DOUBLE_LAYER_INHANCE",
        UPDATA_MAINMENUSCENE_ICON = "NotificationTag_UPDATE_MAINMENU_ICON",
        REPEAT_FIGHTING_ANIMATION = "NotificationTag_REPEAT_FIGHTING_ANIMATION"
	}
}